version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - REACT_APP_WEBSOCKET_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    image: real-time-github-contribution-graph-backend
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
