version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/github-contributions
      - REDIS_URL=redis://redis:6379
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - REACT_APP_WEBSOCKET_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
