# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Change the working directory to /app/src
WORKDIR /app/src

# Expose the backend port
EXPOSE 5000

# Start the application
CMD ["node", "index.js"]
